# Définit où est le code source métier (exclut les tests)
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Définit où sont les tests
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
