@startuml ResetPassword


title Reset Password (Secure Flow)

actor User
participant Front
participant Back
participant Redis
participant Database
participant SMTP

note over User, SMTP: Phase 2 : Définition du nouveau mot de passe

SMTP->User: Reçoit l'email
User->Front: Clique sur le lien /reset-password?token=xyz
Front->User: Affiche le formulaire "Nouveau mot de passe"

User->Front: Saisit le nouveau mot de passe + Confirmation
Front->Back: POST /auth/reset-password { token, newPassword }

Back->Redis: GET "reset:token-uuid"
Redis->Back: Retourne userId ou Null

alt Token Invalide ou Expiré
    Back->Front: 400 Bad Request { error: "Link expired" }
    Front->User: Affiche "Le lien a expiré, veuillez recommencer"
else Token Valide
    Back->Back: Hash le nouveau mot de passe (Argon2)
    Back->Database: Update User Password
    
    # Nettoyage de sécurité
    Back->Redis: DEL "reset:token-uuid"
    note right of Redis: Empêche la réutilisation du lien
    
    Back->Front: 200 OK
    Front->User: Affiche "Mot de passe modifié avec succès"
    Front->User: Redirige vers /login
end