name: Backend CI
permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [develop]
    paths:
      - "backend/**"
  pull_request:
    branches: [develop]
    paths:
      - "backend/**"

jobs:
  call-ci-common:
    uses: ./.github/workflows/ci-common.yml
    with:
      path: ./backend
      node-version: "24"
    secrets: inherit
