name: Manage automerge label

permissions:
  contents: write
  issues: write
  pull-requests: write
on:
  pull_request:
    types: [opened, reopened]
  check_suite:
    types: [completed]

jobs:
  add-label-on-success:
    if: github.event_name == 'check_suite' && github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated pull request
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.payload.check_suite.head_branch}`,
              state: 'open'
            });

            return pulls.length > 0 ? pulls[0].number : '';

      - name: Add automerge label if all checks succeed
        if: steps.find-pr.outputs.result != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
          number: ${{ steps.find-pr.outputs.result }}

  remove-label-on-failure:
    if: github.event_name == 'check_suite' && github.event.check_suite.conclusion != 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated pull request
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${context.payload.check_suite.head_branch}`,
              state: 'open'
            });

            return pulls.length > 0 ? pulls[0].number : '';

      - name: Remove automerge label if checks failed
        if: steps.find-pr.outputs.result != ''
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
          number: ${{ steps.find-pr.outputs.result }}
